### ISSUE TITLE
How I can do face recognition? 

### ISSUE THREAD

**Issue by datomnurdin** [NVentimiglia/ISeeYou-Augmented-Reality-Face-Recognition#1]
As per subject, is it possible to do face recognition using Metaio SDK which is comparing it with existing database to check either is it match or not. Please advice. Thank you.

**Comment by NVentimiglia** [comment]
Metaio only has image recognition. That is to say it can identify where a face is within a video stream. Facial comparison is what you need.

**Comment by datomnurdin** [comment]
So is it supported?

**Comment by NVentimiglia** [comment]
No
